### ISSUE TITLE
Having to include the CLP(FD) library is not explicit enough

### ISSUE THREAD

**Issue by JCumin** [triska/the-power-of-prolog#4]
Take for example the second chapter "Facets of Prolog". In this chapter, there is the following code example:

```
list_length([], 0).
list_length([_|Ls], N) :-
        N #> 0,
        N #= N0 + 1,
        list_length(Ls, N0).
```

If the reader does not bother reading the "Integer Arithmetic" chapter first (which is linked in the previous sentence, but I assume newcomers would not follow those links right away), then the reader has no idea that they have to add `:- use_module(library(clpfd)).` with most distributions.

This lead people in [the Prolog learning chatroom](https://chat.stackexchange.com/rooms/74093/prolog) to [not understand why a simple first Prolog example did not work](https://chat.stackexchange.com/transcript/message/43253765#43253765), or even to [conclude that the code exposed in The Power of Prolog is a not a standard dialect of Prolog](https://chat.stackexchange.com/transcript/message/43254500#43254500).

**Comment by triska** [comment]
Good point, thank you! I have added a more explicit usage note, please have a look.

Here is a bit more background information about this issue: The snippet already works *as&nbsp;is* with systems such as GNU-Prolog and B-Prolog, but currently only works if you include a library in other systems. One of my strategic goals is to make declarative integer arithmetic a **first&nbsp;class citizen** in as many Prolog systems as possible and thus increase compatibility between systems.

In my experience, the suggestion of a single person is not enough to effect such a development, no matter how you phrase&nbsp;it. As one attempt to solve this issue, I typically present the code *as&nbsp;if* the systems had already undergone this development, in the hope to get more users accustomed to how things *could&nbsp;be*, and to see the benefit more directly.

It is my hope that with enough interest from application programmers, we can together achieve more than a single person can&nbsp;do, and make declarative features more readily available in Prolog&nbsp;systems!

Where I taught Prolog, the struggle of undergraduates with low-level integer arithmetic is still legendary even though constraints have long since been enabled by default in all system&nbsp;installations. I think that more declarative methods are much easier to teach and understand.

**Comment by JCumin** [comment]
Simple but most likely effective change, thank you.
